### PR TITLE
Modified code to only save data when data is actually modified, removed redundant images, and indexed skins from zero.

### PR DESCRIPTION
**Pull request by 0gb-us**
Skin # 1 (both 2D and 3D) were already present in default. I removed the duplicates from skins, and added the default image names ("player" and "character") to the skin list.

That left skins being numbered from two, which was even odder than numbering from one, so since I needed to rename the files anyway, I numbered them from zero this time.

Previously, the skin file was saved every time the user logs in. That seems unnecessary, so I modified the code to save the file only when the data actually changes.

### CODE REVIEW

**Comment by Zeg9** [comment]
I would merge this, but people who have this installed on servers might have some custom skins and would have to rename all of them because of starting from zero :/

**Comment by 0gb-us** [comment]
Yeah. I thought about that, and figured it was better now than later, and better to change it than leave things indexed from two.

I could scrap the whole fork and refork (to put the images back) and resubmit this with the images indexed from two if you would like. Anyone using skin one would end up with a broken image as a skin, but the others would all be intact. Would you be interested in that?

**Comment by Zeg9** [comment]
This wouldn't be good either... Maybe we should find a way to list skins with something like "ls" command but it wouldn't be portable anymore =/

**Comment by 0gb-us** [comment]
I'm sorry then, I don't know what to do. There's no (non-hacky) way to avoid breaking at least one skin while also removing the redundant skin. It seems pointless to have both character and character_1 (which are the exact same skin, but separate image files) as well as both character and character_1 (same issue).

Then again, if this isn't the kind of thing you'd want to alter in your plugin, let me know. I'm not trying to be pushy or anything.

**Comment by 0gb-us** [comment]
Withdrawing pull request. I don't think there is a way to both optimise and maintain backward compatibility. I've already forked this for use in 0gb.us_game anyway, so I can go a slightly different direction anyway.

Thank you so much for building this! I wouldn't have been able to figure out how to flip between 2D and 3D skins without looking at your code.

**Pull request closed without merging**
