### PR TITLE
add more skins

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by HybridDog** [comment]
something happened to the mouth of your skin

**Comment by Zeg9** [comment]
I didn't ask you, but who made these and what's the license?

**Comment by Zeg9** [comment]
About the mouth, I think you may not have the same blender version as me... I'm on 2.66a, what's yours?

**Comment by HybridDog** [comment]
I made the textures (WTFPL)
I'm using blender 2.62
I need a new version
https://launchpad.net/ubuntu/+source/blender

**Comment by Zeg9** [comment]
Okay, I see. They probably modified the renderer between versions, but that doesn't matter. I'll add credit to you on the forum post, and soon add a readme (and re-build the previews)

**Comment by HybridDog** [comment]
Now I'm using blender 2.67.1.

**Comment by Zeg9** [comment]
Oh I should update then... Have 600MB of updates to download -.-... With my fabulous connection... ok this has nothing to do with it, but...

**Pull request merged**
